# taps a-z

tap "homebrew/cask"
tap "heroku/brew"
tap "teamookla/speedtest"
tap "vapor/tap"

# formulaes a-z

brew "atuin"
brew "carthage"
brew "cmake"
brew "cocoapods"
brew "ctags"
brew "docker"
brew "duti"
brew "ethereum"
brew "heroku/brew/heroku"
brew "kylef/formulae/swiftenv"
brew "lazygit"
brew "libtool"
brew "llvm"
brew "mint"
brew "neovim"
brew "node"
brew "python@3.10"
brew "ruby"
brew "rustup-init"
brew "speedtest"
brew "sqlite"
brew "swiftformat"
brew "swiftlint"
brew "tmux"
brew "tree"
brew "tree-sitter"
brew "vapor"
brew "zoxide"

# casks a-z

cask "adguard"
cask "discord"
cask "eul"
cask "gitkraken"
cask "iterm2"
cask "kap"
cask "karabiner-elements"
cask "postman"
cask "proxyman"
cask "rectangle"
cask "sf-symbols"
cask "visual-studio-code"
cask "transmission"
cask "wireshark"
